#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# seamm_webui documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# Get the project root dir, which is the parent dir of this
cwd = os.getcwd()
project_root = os.path.dirname(cwd)

# Insert the project root dir as the first element in the PYTHONPATH.
# This lets us ensure that the source package is imported, and that its
# version is used.
sys.path.insert(0, project_root)

import seamm_webui  # noqa: E402

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx_design',
    'sphinx_copybutton',
    'sphinx.ext.todo',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'seamm_webui'
copyright = u"2026, Molecular Sciences Software Institute (MolSSI)"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = seamm_webui.__version__
# The full version, including alpha/beta/rc tags.
release = seamm_webui.__version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "github_url": "https://github.com/molssi-seamm/seamm_webui",
    "twitter_url": "https://twitter.com/MolSSI_NSF",
    "icon_links": [],
    "logo": {
        "image_light": "SEAMM logo.png",
        "image_dark": "SEAMM inverted.png",
        "text": "seamm_webui",
        "molssi_light": "molssi_main_logo.png",
        "molssi_dark": "molssi_main_logo_inverted_white.png",
    },
    "show_toc_level": 2,
    "header_links_before_dropdown": 4,
    "external_links": [
        {"name": "SEAMM Documentation", "url": "https://molssi-seamm.github.io"},
        {"name": "MolSSI", "url": "https://molssi.org"}
    ],
    "secondary_sidebar_items": ["page-toc", "sourcelink"],
    "footer_items": ["molssi_footer"],
}

# Add any paths that contain custom static files (such as style sheets)
# here, relative to this directory. They are copied after the builtin
# static files, so a file named "default.css" will overwrite the builtin
# "default.css".
html_static_path = ['_static']

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'css/custom.css',
]

# If true, "Created using Sphinx" is shown in the HTML footer.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer.
html_show_copyright = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'seamm_webuidoc'


# -- Options for LaTeX output ------------------------------------------

latex_elements = {}

latex_documents = [
    ('index', 'seamm_webui.tex',
     u'seamm_webui Documentation',
     u'Paul Saxe', 'manual'),
]


# -- Options for manual page output ------------------------------------

man_pages = [
    ('index', 'seamm_webui',
     u'seamm_webui Documentation',
     [u'Paul Saxe'], 1)
]


# -- Options for Texinfo output ----------------------------------------

texinfo_documents = [
    ('index', 'seamm_webui',
     u'seamm_webui Documentation',
     u'Paul Saxe',
     'seamm_webui',
     'SPA-based web dashboard for SEAMM.',
     'Miscellaneous'),
]
